//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXeKhach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENLAI
    {
        public string IDBienLai { get; set; }
        public string IDGhe { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string GiamGia { get; set; }
        public string ThuNgan { get; set; }
        public string TenHanhKhach { get; set; }
        public string SoDienThoaiHK { get; set; }
    
        public virtual GHE GHE { get; set; }
        public virtual THUNGAN THUNGAN1 { get; set; }
    }
}
