//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXeKhach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANHKHACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANHKHACH()
        {
            this.BIENLAIs = new HashSet<BIENLAI>();
        }
    
        public string IDHanhKhach { get; set; }
        public string SoHieuGhe { get; set; }
        public string TenHanhKhach { get; set; }
        public string GioiTinh { get; set; }
        public string Tuoi { get; set; }
        public string CCCD { get; set; }
        public string SDTHK { get; set; }
        public string DiaChiHK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENLAI> BIENLAIs { get; set; }
        public virtual GHE GHE { get; set; }
    }
}
