//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXeKhach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUUTHONG
    {
        public string IDTuyenXe { get; set; }
        public string BienSoXe { get; set; }
        public Nullable<byte> TongKhach { get; set; }
        public string IDBenDau { get; set; }
        public string IDBenCuoi { get; set; }
        public Nullable<System.DateTime> ThoiGianXuatPhat { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string ChiTietTram { get; set; }
    
        public virtual XEKHACH XEKHACH { get; set; }
        public virtual TUYENXE TUYENXE { get; set; }
    }
}
