//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXeKhach.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLXEKHACHEntities1 : DbContext
    {
        public QLXEKHACHEntities1()
            : base("name=QLXEKHACHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENXE> BENXEs { get; set; }
        public virtual DbSet<BIENLAI> BIENLAIs { get; set; }
        public virtual DbSet<GHE> GHEs { get; set; }
        public virtual DbSet<HANHKHACH> HANHKHACHes { get; set; }
        public virtual DbSet<LICHTRINH> LICHTRINHs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<TAIXE> TAIXEs { get; set; }
        public virtual DbSet<THUNGAN> THUNGANs { get; set; }
        public virtual DbSet<TUYENXE> TUYENXEs { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<XEKHACH> XEKHACHes { get; set; }
    }
}
