//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXeKhach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCO
    {
        public string IDsuco { get; set; }
        public string BienSoXe { get; set; }
        public string TenSuCo { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayGapSuCo { get; set; }
    
        public virtual XEKHACH XEKHACH { get; set; }
    }
}
