//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXeKhach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYENXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYENXE()
        {
            this.XEKHACHes = new HashSet<XEKHACH>();
        }
    
        public string IDTuyenXe { get; set; }
        public string IDBenXeXuatPhat { get; set; }
        public string IDBenKetThuc { get; set; }
        public Nullable<System.DateTime> ThoiGianXuatPhat { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
    
        public virtual BENXE BENXE { get; set; }
        public virtual BENXE BENXE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XEKHACH> XEKHACHes { get; set; }
    }
}
